import { Icon } from "@iconify/react";
import Head from "next/head";
import Link from "next/link";
import SliderSection from "@/components/SliderSection";
import TestimonialsSlider from "@/components/TestimonialsSlider";
import Slider from "react-slick";
import Image from "next/image";

export default function Home() {
  const settings = {
    dots: true,
    infinite: true,
    slidesToShow: 1,
    slidesToScroll: 1,
    vertical: true,
    verticalSwiping: true,
    autoplay: true,
    speed: 500,
  };
  return (
    <>
      <Head>
        <title>Bharat Pharmatech</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <section className="hero-section w-full md:h-[550px] md:flex border-b">
        <div className="md:w-[50%] bg-black text-white h-full p-5 flex items-center">
          <div className="py-10">
            <h1 className="text-5xl font-bold">Bharat Pharmatech</h1>
            <h2 className="text-xl font-medium">
              Brand Of Pharma Machinery & Spares
            </h2>
            <p className="mt-5">
              Lorem ipsum dolor sit amet consectetur adipisicing elit. Quidem
              quaerat delectus commodi expedita modi cum iusto at nisi? Quidem,
              provident natus possimus assumenda tenetur quo excepturi
              voluptatum. Cum, officia odit.
            </p>
            <div>
              <button className="px-5 py-2 rounded-full bg-white text-black mt-5 font-medium">
                Products
              </button>
              <button className="px-5 underline underline-offset-4">
                Learn More
              </button>
            </div>
          </div>
        </div>
        <div className="md:w-[50%] h-full md:block hidden">
          <div className="sliders-asdf h-full">
            <Slider {...settings}>
              <div>
                <h2 className="text-3xl px-5 py-3 font-semibold">
                  Granulation Machinery
                </h2>
                <div className="grid grid-rows-2 gap-3 px-5 grid-cols-2">
                  <div className="w-full m-0 h-[220px]">
                    <Image
                      src={"https://source.unsplash.com/random"}
                      width="500"
                      height={500}
                      className="h-full w-full object-cover"
                    />
                  </div>
                  <div className="w-full m-0 h-[220px]">
                    <Image
                      src={"https://source.unsplash.com/random"}
                      width="500"
                      height={500}
                      className="h-full w-full object-cover"
                    />
                  </div>
                  <div className="w-full m-0 h-[220px]">
                    <Image
                      src={"https://source.unsplash.com/random"}
                      width="500"
                      height={500}
                      className="h-full w-full object-cover"
                    />
                  </div>
                  <div className="w-full m-0 h-[220px]">
                    <Image
                      src={"https://source.unsplash.com/random"}
                      width="500"
                      height={500}
                      className="h-full w-full object-cover"
                    />
                  </div>
                </div>
              </div>
              <div>
                <h2 className="text-3xl px-5 py-3 font-semibold">
                  Granulation Machinery
                </h2>
                <div className="grid grid-rows-2 gap-3 px-5 grid-cols-2">
                  <div className="w-full m-0 h-[220px]">
                    <Image
                      src={"https://source.unsplash.com/random"}
                      width="500"
                      height={500}
                      className="h-full w-full object-cover"
                    />
                  </div>
                  <div className="w-full m-0 h-[220px]">
                    <Image
                      src={"https://source.unsplash.com/random"}
                      width="500"
                      height={500}
                      className="h-full w-full object-cover"
                    />
                  </div>
                  <div className="w-full m-0 h-[220px]">
                    <Image
                      src={"https://source.unsplash.com/random"}
                      width="500"
                      height={500}
                      className="h-full w-full object-cover"
                    />
                  </div>
                  <div className="w-full m-0 h-[220px]">
                    <Image
                      src={"https://source.unsplash.com/random"}
                      width="500"
                      height={500}
                      className="h-full w-full object-cover"
                    />
                  </div>
                </div>
              </div>
              <div>
                <h2 className="text-3xl px-5 py-3 font-semibold">
                  Granulation Machinery
                </h2>
                <div className="grid grid-rows-2 gap-3 px-5 grid-cols-2">
                  <div className="w-full m-0 h-[220px]">
                    <Image
                      src={"https://source.unsplash.com/random"}
                      width="500"
                      height={500}
                      className="h-full w-full object-cover"
                    />
                  </div>
                  <div className="w-full m-0 h-[220px]">
                    <Image
                      src={"https://source.unsplash.com/random"}
                      width="500"
                      height={500}
                      className="h-full w-full object-cover"
                    />
                  </div>
                  <div className="w-full m-0 h-[220px]">
                    <Image
                      src={"https://source.unsplash.com/random"}
                      width="500"
                      height={500}
                      className="h-full w-full object-cover"
                    />
                  </div>
                  <div className="w-full m-0 h-[220px]">
                    <Image
                      src={"https://source.unsplash.com/random"}
                      width="500"
                      height={500}
                      className="h-full w-full object-cover"
                    />
                  </div>
                </div>
              </div>
            </Slider>
          </div>
          {/* <Slider {...settings}>
            <div className="w-full h-[200px]">
              <div className="bg-gray-100 w-full h-full">
                <p>hellw</p>
              </div>
            </div>
            <div className="w-full h-[200px]">
              <div className="bg-gray-100 w-full h-full">
                <p>hellw</p>
              </div>
            </div>
            <div className="w-full h-[200px]">
              <div className="bg-gray-100 w-full h-full">
                <p>hellw</p>
              </div>
            </div>
            <div className="w-full h-[200px]">
              <div className="bg-gray-100 w-full h-full">
                <p>hellw</p>
              </div>
            </div>
          </Slider> */}
          {/* <div className="flex flex-wrap h-4/5 px-5">
            <div className="w-1/2 h-1/2">
              <div className="bg-gray-100 w-full h-full"></div>
            </div>
          </div> */}
        </div>
      </section>
      <section className="about-section md:flex px-5 pt-10">
        <div className="md:block hidden w-[40%] bg-gray-50"></div>
        <div className="flex-1 md:pl-10">
          <h2 className="lg:text-5xl md:text-4xl text-3xl font-bold">
            Bharat Pharmatech
          </h2>
          <h3 className="text-2xl font-medium">Our Brand, Your Trust</h3>
          <p className="mt-5">
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Quibusdam
            harum consequuntur consequatur deserunt eos ipsa. Dolores illo dicta
            numquam mollitia sapiente odit corrupti tenetur rerum vero, at cum,
            consectetur sed? Expedita facere ipsum sed vero recusandae quidem
            odit aliquam, qui architecto ducimus reiciendis,
            <br />
            <br />
            culpa asperiores cumque ab quae error. Qui, saepe vel error quaerat
            animi placeat voluptate. Maiores, obcaecati repellat! Assumenda qui
            molestiae nihil.
          </p>
          <div className="mt-5">
            <h2 className="text-3xl font-semibold">Why Choose Us?</h2>
            <ul className="mt-3">
              <li className="flex gap-4 items-center my-4">
                <Icon
                  className="md:text-3xl text-2xl shrink-0"
                  icon="teenyicons:tick-circle-solid"
                />
                <span>
                  Lorem ipsum dolor, sit amet consectetur adipisicing elit. Quas
                  facere repudiandae
                </span>
              </li>
            </ul>
          </div>
          <Link
            href={"/"}
            className="block px-7 w-fit mt-5 py-3 bg-black text-white rounded-full"
          >
            Learn More
          </Link>
        </div>
      </section>
      <SliderSection heading={"Tablet Press Machinery"} />
      <SliderSection heading={"Granulation Machinery"} />
      <SliderSection heading={"Roll Compactor Machinery"} />
      <section className="testimonial-section px-5 my-10 py-10 bg-black text-white">
        <h2 className="text-4xl font-bold">Testimonials</h2>
        <p className="text-2xl font-semibold">
          They Loved Our Products, So will you
        </p>
        <br />
        <TestimonialsSlider />
      </section>
    </>
  );
}
